base_url:
#  ukuaiqi: https://ukuaiqi.com     # 正式环境
  ukuaiqi: http://staging.ukuaiqi.com     # staging
  EDP: https://admin.edpglobal.cn  # 正式环境
excel_parameter:
  project_name: 快启
  science: 正式环境
config:
  level: 10